<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>a82704d2-f5b7-4b80-a4df-7c02be280dd0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="MassTransit" Version="[8.*,9.0)" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Openlysis.Application\Openlysis.Application.csproj" />
    <ProjectReference Include="..\..\Analyzers\Openlysis.Analyzers.Filescan\Openlysis.Analyzers.Filescan.csproj" />
    <ProjectReference Include="..\..\Analyzers\Openlysis.Analyzers.HybridAnalysis\Openlysis.Analyzers.HybridAnalysis.csproj" />
    <ProjectReference Include="..\..\Analyzers\Openlysis.Analyzers.URLQuery\Openlysis.Analyzers.URLQuery.csproj" />
    <ProjectReference Include="..\..\Analyzers\Openlysis.Analyzers.VirusTotal\Openlysis.Analyzers.VirusTotal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Broker\" />
  </ItemGroup>
</Project>
