using Openlysis.Domain.Common.Enums;
using Openlysis.Domain.Files.Entities;

namespace Openlysis.API.Endpoints.Files.Common.Responses;

/// <summary>
/// Represents the analysis result from a specific service.
/// </summary>
/// <param name="Id">The unique identifier of the file service analysis.</param>
/// <param name="JobId">The optional job identifier associated with the analysis.</param>
/// <param name="ServiceName">The name of the service that performed the analysis.</param>
/// <param name="Status">The status of the analysis performed by the service.</param>
/// <param name="Verdict">The verdict of the analysis performed by the service.</param>
/// <param name="ThreatZone">The threat zone classification of the analysis.</param>
/// <param name="Reports">The collection of reports generated by the service analysis.</param>
public record FileServiceAnalysisDto(
    string Id,
    string? JobId,
    string ServiceName,
    AnalysisStatus Status,
    Verdict Verdict,
    ThreatZone ThreatZone,
    FileReportDto[] Reports)
{
    /// <summary>
    /// Converts a <see cref="FileServiceAnalysis"/> instance to a <see cref="FileServiceAnalysisDto"/>.
    /// </summary>
    /// <param name="source">The source <see cref="FileServiceAnalysis"/> object to be converted.</param>
    /// <returns>A new <see cref="FileServiceAnalysisDto"/> instance containing the converted data.</returns>
    public static FileServiceAnalysisDto Parse(FileServiceAnalysis source)
    {
        FileReportDto[] reports = source.Reports
            .Select(FileReportDto.Parse)
            .ToArray();

        return new FileServiceAnalysisDto(
            source.Id.Primary.Value,
            source.Id.Job,
            source.ServiceName,
            source.State.Status,
            source.State.Verdict,
            source.State.ThreatZone,
            reports);
    }
}