using Openlysis.Domain.Common.Enums;
using Openlysis.Domain.Files.Entities;

namespace Openlysis.API.Endpoints.Files.Common.Responses;

/// <summary>
/// Data transfer object for <see cref="FileAnalysis"/>.
/// </summary>
/// <param name="Id">The unique identifier of the file service analysis.</param>
/// <param name="JobId">The optional job identifier associated with the analysis.</param>
/// <param name="ServiceName">The name of the service that performed the analysis.</param>
/// <param name="Status">The status of the analysis performed by the service.</param>
/// <param name="Verdict">The verdict of the analysis performed by the service.</param>
/// <param name="ThreatZone">The threat zone classification of the analysis.</param>
/// <param name="ThreatScore">The threat score assigned by the service.</param>
/// <param name="Reports">The collection of reports generated by the service analysis.</param>
public record FileAnalysisDto(
    string Id,
    string? JobId,
    string ServiceName,
    AnalysisStatus Status,
    Verdict Verdict,
    ThreatZone ThreatZone,
    int? ThreatScore,
    FileReportDto[] Reports)
{
    /// <summary>
    /// Converts a <see cref="FileAnalysis"/> instance to a <see cref="FileAnalysisDto"/>.
    /// </summary>
    /// <param name="source">The source <see cref="FileAnalysis"/> object to be converted.</param>
    /// <returns>A new <see cref="FileAnalysisDto"/> instance containing the converted data.</returns>
    public static FileAnalysisDto Parse(FileAnalysis source)
    {
        FileReportDto[] reports = source.Reports
            .Select(FileReportDto.Parse)
            .ToArray();

        return new FileAnalysisDto(
            source.ExternalId.Primary,
            source.ExternalId.Job,
            source.ExternalId.Service,
            source.State.Status,
            source.State.Verdict,
            source.State.ThreatZone,
            source.ThreatScore.NormalizedValue,
            reports);
    }
}