namespace Openlysis.API.Endpoints.Files.Common.Responses;

/// <summary>
/// Represents the analysis result from a specific service.
/// </summary>
/// <param name="ServiceName">The name of the service that performed the analysis.</param>
/// <param name="Status">The status of the analysis performed by the service.</param>
/// <param name="Reports">The collection of reports generated by the service analysis.</param>
public record ServiceFileAnalysisDto(
    string ServiceName,
    string Status,
    IEnumerable<ReportDto> Reports);