using System.Text.Json.Serialization;

using Openlysis.Analyzers.URLQuery.Core.Models.Enums;

namespace Openlysis.Analyzers.URLQuery.Core.Models.Objects;

// String values to determine verdict.
// Malicious - phishing, malware, malicious, scam, fraud.
// Suspicious - suspicious
// Undetected - undetected, clean, benign, nothreat,
// Unknown - unknown.

/// <summary>
/// Represents an alert generated by an analyzer.
/// </summary>
/// <param name="Severity">The severity level of the alert.</param>
/// <param name="Verdict">The verdict of the alert, which should be replaced with an enum.</param>
public record AnalyzerAlert(
    Severity Severity,
    [property: JsonPropertyName("verdict")] string Verdict)
    : Alert(Severity);