using System.Text.Json.Serialization;

using Openlysis.Analyzers.URLQuery.Core.Models.Enums;

namespace Openlysis.Analyzers.URLQuery.Core.Models.Objects;

/// <summary>
/// Represents an alert generated by an analyzer.
/// </summary>
/// <param name="Severity">The severity level of the alert.</param>
/// <param name="Verdict">The verdict of the alert, which should be replaced with an enum.</param>
public record AnalyzerAlert(
    string Message,
    Severity Severity,
    [property: JsonPropertyName("verdict")] string Verdict)
    : Alert(Message, Severity);