@OpenlysisAPIHostAddress = http://localhost:5248/api/v1
@SampleFileAnalysisId = 16351fe3-d1ad-41c3-9e52-9a8396c2519d
@SampleFileAnalysisSha256 = 24B0AC1FCEAFD2100E112E2B66D8832979CB3036F8C3EF3965EAEE22DFD1604D

// Get by ID
GET {{OpenlysisAPIHostAddress}}/analyses/file/{{SampleFileAnalysisId}}
Accept: application/json
###

// Get by hash
GET {{OpenlysisAPIHostAddress}}/analyses/file/hash/{{SampleFileAnalysisSha256}}
Accept: application/json
###

// Analyze file
POST {{OpenlysisAPIHostAddress}}/analyses/file
Accept: application/json
Content-Type: multipart/form-data; boundary=Boundary

--Boundary
Content-Disposition: form-data; name="file"; filename="openlysis-test.txt"
Content-Type: text/plain; charset=UTF-8

This is a sample text from openlysis
--Boundary
Content-Disposition: form-data; name="reanalyze";
Content-Type: text/plain

true
--Boundary
###